CXX=g++

all: maptest0 maptest1 maptest2 maptest3 maptest4 maptest5 maptest6 maptest7 maptest8

mapTest: map.h map.cpp mapTest.cpp
	clear
	$(CXX) -g mapTest.cpp -o mapTest

maptest0: map.h map.cpp maptest0.cpp
	clear
	$(CXX) -g maptest0.cpp -o maptest0

maptest1: map.h map.cpp maptest1.cpp
	clear
	$(CXX) -g maptest1.cpp -o maptest1

maptest2: map.h map.cpp maptest2.cpp
	clear
	$(CXX) -g maptest2.cpp -o maptest2

maptest3: map.h map.cpp maptest3.cpp
	clear
	$(CXX) -g maptest3.cpp -o maptest3

maptest4: map.h map.cpp maptest4.cpp
	clear
	$(CXX) -g maptest4.cpp -o maptest4

maptest5: map.h map.cpp maptest5.cpp
	clear
	$(CXX) -g maptest5.cpp -o maptest5

maptest6: map.h map.cpp maptest6.cpp
	clear
	$(CXX) -g maptest6.cpp -o maptest6

maptest7: map.h map.cpp maptest7.cpp
	clear
	$(CXX) -g maptest7.cpp -o maptest7

maptest8: map.h map.cpp maptest8.cpp
	clear
	$(CXX) -g maptest8.cpp -o maptest8

clean:
	rm -f *.o  mapTest maptest0 maptest1 maptest2 maptest3 maptest4 maptest5 maptest6 maptest7 maptest8


